#constants.py
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 1000
SCREEN_MARGIN = 20


WALL_PIXEL_SIZE = 30
WALL_SHAPE_SIZE = WALL_PIXEL_SIZE / 20
WALL_SHAPE_HEIGHT = SCREEN_HEIGHT / 20


PLAT_PIXEL_SIZE = 30
PLAT_SHAPE_SIZE = PLAT_PIXEL_SIZE / 20
FLOOR_PIXEL_LENGTH = SCREEN_WIDTH - 2 * (WALL_PIXEL_SIZE + SCREEN_MARGIN)
FLOOR_SHAPE_LENGTH = FLOOR_PIXEL_LENGTH / 20
GROUND_Y = -SCREEN_HEIGHT / 2 + 50


PLAYER_PIXEL_SIZE = 40
PLAYER_SHAPE_SIZE = PLAYER_PIXEL_SIZE / 20
PLAYER_START_Y = GROUND_Y + (PLAT_PIXEL_SIZE + PLAYER_PIXEL_SIZE) / 2

HALF_SCREEN_HEIGHT = SCREEN_HEIGHT // 2
HALF_SCREEN_WIDTH = SCREEN_WIDTH // 2
HALF_PLAYER_SIZE = PLAYER_PIXEL_SIZE // 2
HALF_PLAT_SIZE = PLAT_PIXEL_SIZE // 2
PLATFORM_GAP = PLAYER_PIXEL_SIZE + PLAT_PIXEL_SIZE + SCREEN_MARGIN
FRAME_TIME = 1000 // 60  # 60 FPS

GRAVITY = 1
FRICTION = 0.9
JUMP_DISTANCE = 14
JUMP_FACTOR = 0.75
WALL_BOUNCE_FACTOR = 0.75
ACCELERATION = 0.5
MAX_SPEED = 15
TURN_FACTOR = 5
ROTATION_SPEED = 10


SCROLL_THRESHOLD = -SCREEN_HEIGHT / 4
FAST_SCROLL_Y = SCREEN_HEIGHT / 4
FAST_SCROLL_SPEED = 8
MAX_SCROLL_SPEED = 4

BONUS_CHANCE = 0.25

# pre-calculate common values to avoid repeated calculations
PLAYER_HALF_SIZE = PLAYER_PIXEL_SIZE * 0.5
PLAT_HALF_SIZE = PLAT_PIXEL_SIZE * 0.5
WALL_HALF_SIZE = WALL_PIXEL_SIZE * 0.5
PLAYER_COLLISION_TOLERANCE = PLAYER_PIXEL_SIZE / 3
AIR_FRICTION = 0.98
TURN_ACCELERATION = ACCELERATION * TURN_FACTOR
NEG_MAX_SPEED = -MAX_SPEED
CELEBRATION_THRESHOLD = 24.5